<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>HrmLoginTestSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>2</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>bc81f765-2e57-4e7a-ab6d-2569dd424bae</testSuiteGuid>
   <testCaseLink>
      <guid>7c4e901f-9e86-4d96-b9ea-dc09c58faa86</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/OrangeHrm/CucumberTest/RunFeatureFolder</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb3e8052-b681-4bdc-9ea9-04ae8eb18cfb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f63bf6b8-c3c5-4538-b16f-751584b4a534</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ff63f8f0-a648-41d8-ac58-b98467c3133e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/OrangeHrm/CucumberTest/RunSpecificFeature</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe427190-a275-4b8a-b65c-76d4d03ae124</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d4945f4-d33f-4139-ae5f-40c9392f7a8c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2b1b0ebf-4670-49af-80cd-8e72d404ef05</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/OrangeHrm/CucumberTest/RunThroughRunnerFile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4dde3e7-728a-47c0-b73b-dea156f77b1f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ff6f220-251e-40a5-8447-b258a7b36f20</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
